services:
  dpc-mc-server:
    build: .
    image: dpc-mc-server
    container_name: dpc-mc-server
    ports:
      - "25565:25565"
    restart: unless-stopped
    volumes:
      - type: volume
        source: dpcmcserver
        target: /dpcmcserver
      - type: bind
        source: ./deposit-box
        target: /deposit-box

volumes:
  dpcmcserver: