services:
  testmcserver:
    build: .
    image: dpc-mc-server
    container_name: dpc-mc-server
    ports:
      - "25565:25565"
      - "8123:8123"
      - "8100:8100"
    volumes:
      - type: volume
        source: dpcmcserver
        target: /dpcmcserver
      - type: bind
        source: ./deposit-box
        target: /deposit-box
    environment:
      - MINECRAFT_VERSION=${MINECRAFT_VERSION}
      - OPERATOR_UUID=${OPERATOR_UUID}
      - OPERATOR_NAME=${OPERATOR_NAME}
      - OPERATOR_LEVEL=${OPERATOR_LEVEL}
      - OVERWRITE_EXISTING_SERVER=${OVERWRITE_EXISTING_SERVER}
      - ACTIVITY_TRACKER_ENABLED=${ACTIVITY_TRACKER_ENABLED}
      - ALTERNATE_ACCOUNT_FINDER_ENABLED=${ALTERNATE_ACCOUNT_FINDER_ENABLED}
      - CURRENCIES_ENABLED=${CURRENCIES_ENABLED}
      - DANS_ESSENTIALS_ENABLED=${DANS_ESSENTIALS_ENABLED}
      - DANS_SET_HOME_ENABLED=${DANS_SET_HOME_ENABLED}
      - DANS_SPAWN_SYSTEM_ENABLED=${DANS_SPAWN_SYSTEM_ENABLED}
      - FIEFS_ENABLED=${FIEFS_ENABLED}
      - FOOD_SPOILAGE_ENABLED=${FOOD_SPOILAGE_ENABLED}
      - MEDIEVAL_ECONOMY_ENABLED=${MEDIEVAL_ECONOMY_ENABLED}
      - MEDIEVAL_FACTIONS_ENABLED=${MEDIEVAL_FACTIONS_ENABLED}
      - MEDIEVAL_ROLEPLAY_ENGINE_ENABLED=${MEDIEVAL_ROLEPLAY_ENGINE_ENABLED}
      - MORE_RECIPES_ENABLED=${MORE_RECIPES_ENABLED}
      - NETHER_ACCESS_CONTROLLER_ENABLED=${NETHER_ACCESS_CONTROLLER_ENABLED}
      - NO_MORE_CREEPERS_ENABLED=${NO_MORE_CREEPERS_ENABLED}
      - PLAYER_LORE_ENABLED=${PLAYER_LORE_ENABLED}
      - SIMPLE_SKILLS_ENABLED=${SIMPLE_SKILLS_ENABLED}
      - WILD_PETS_ENABLED=${WILD_PETS_ENABLED}
      - BLUEMAP_ENABLED=${BLUEMAP_ENABLED}
      - DYNMAP_ENABLED=${DYNMAP_ENABLED}
      - PLACEHOLDER_API_ENABLED=${PLACEHOLDER_API_ENABLED}
      - VIA_BACKWARDS_ENABLED=${VIA_BACKWARDS_ENABLED}
      - VIA_VERSION_ENABLED=${VIA_VERSION_ENABLED}

volumes:
  dpcmcserver: