services:
  dpc-mc-server-with-dynmap:
    build:
      context: .
      dockerfile: Dockerfile.dynmap
    image: dpc-mc-server-with-dynmap
    container_name: dpc-mc-server-with-dynmap
    ports:
      - "25565:25565"
      - "8213:8123"
    restart: always
    volumes:
      - ./volume-mounts/world:/dpcmcserver/world
      - ./volume-mounts/world_nether:/dpcmcserver/world_nether
      - ./volume-mounts/world_the_end:/dpcmcserver/world_the_end
volumes:
  world:
  world_nether:
  world_the_end: