name: Release

on:
  release:
    types: [ created ]

permissions:
  contents: write

jobs:
  build-and-validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t dpc-mc-server .
